######################################################################
# Automatically generated by qmake (2.01a) dom 8. jun 16:57:03 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += xml

# Input
HEADERS += tareas.h ventana.h taskliststyle.h
SOURCES += ctrlme.cpp tareas.cpp ventana.cpp taskliststyle.cpp